### ISSUE TITLE
On the need to simulate across different ISAs and OSes

### ISSUE THREAD

**Issue by soapdog** [ssb-ngi-pointer/netsim#1]
I decided to write this as a separate issue because it might be out of scope for this version of netsim, and also because I don't want to spam the healthy convo happening on the commit comments with something that might be considered off-topic.

From what I've read on the initial draft, all the simulation is happening under a single operating system and in the same ISA. This means that the implementations being tested are only being tested on a subset where they all run on the exact same hardware/software combo.

I think it would be beneficial if maybe a superset of netsim could be created — or if the feature mentioned here could be folded into netsim — that would enable running a simulation job across different ISAs and Operating Systems. I have an idea about how this could work.

----

This could leverage the [QEMU project](https://www.qemu.org/) and small HD images could be built for each desired combination of isa, operating system, runtime version, we want. By using QEMU the whole aspect of network topology becomes solvable just by tapping using the network features from the emulator, allowing the simulation to create virtual network topologies that from the PoV of the running ssb servers are just as real as anything they might actually encounter IRL.

Go is very good at cross compiling, so netsim could be provided for all these HD images.

This would allow someone who is working with Linux x86_64 machine to test out and simulate how SSB works on arm64 devices, and how replication works across these different boundaries.

----

I understand this is a larger task. It might even be a new task. It might just leverage netsim as it is defined in the initial draft without changing anything about it, but I think it is a worthy thing to have.

**Comment by staltz** [comment]
@soapdog What does simulating across different OSes do for testing aspects like replication and performance?

**Comment by soapdog** [comment]
@staltz the main benefit in my view is enabling one to test different OSes and ISAs without the need to have dedicated hardware, because without it, I fear that the smaller platforms will remain untested.

**Comment by cryptix** [comment]
I'm also not sure what this will offer. C-like software, like Go or Rust, should compile fine no matter what the target and whats tested here IMHO is their implementation.

That being said, the proposed architecture of controlling the peers via TCP/MUXRPC would work as well under qemu or directly on native machines. It just complicates the boot process of them immensely. Personally I'd wait with this until we have a first working version not not complicate things unnecessarily.

**Comment by soapdog** [comment]
Well, you folks know more than I do. That is why I created an issue instead of commenting on the draft, to gather your thoughts. 

I'm going to close this issue since you folks don't feel it is needed, and I don't want to the work without need.

**Comment by clehner** [comment]
I just want to add the following ideas, although I don't necessarily think this issue needs to be reopened:
- Maybe a possible alternative could be to have an implementation shim or proxy that runs the actual implementation on a remote host, e.g. over ssh. That could work with the current proposed design. The remote host could be physical or a VM.
- Testing interop between a little-endian and a big-endian system could be useful for discovering some kinds of bugs.
- Testing with a virtual network, where different implementations have different IP addresses, could make for a more realistic test environment. But it might be good enough to just use different localhost ports - or addresses in `127.0.0.1/8` - which I assume would be the current plan.

**Comment by staltz** [comment]
>     * Testing with a virtual network, where different implementations have different IP addresses, could make for a more realistic test environment. But it might be good enough to just use different localhost ports - or addresses in `127.0.0.1/8` - which I assume would be the current plan.

I also thought of this, maybe using Kubernetes on a Digital Ocean closed virtual network to spawn a ton of peers, but it's an expensive option, and not too easy to implement.

I think it's good to keep in mind the goals of the netsim. It's after all a simulation, not an approximation of real world networks, and the simulation should be as realistic as is _necessary_ to achieve the stated goals, but not more realistic than that if it costs developer time and effort.

**Comment by cblgh** [comment]
Thanks for the comments, everyone—and @soapdog for the initial issue!

I missed out on listing some of the initial constraints we had talked about in a meeting leading up to my taking on this project. They were (roughly):
* assume lan connectivity
* don't try to test network i/o edge-cases  (timeouts, broken connections, ...?)

There are good ideas in this issue convo tho, especially cel's point about trying to use different ports :)
